version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: projeto_t_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootSenha123
      MONGO_INITDB_DATABASE: projeto_t_db
    command: >
      bash -c "
        mongod --bind_ip_all --auth & 
        sleep 5 &&
        mongosh --username root --password rootSenha123 --authenticationDatabase admin <<EOF
          use projeto_t_db;
          db.createUser({user: 'projetot_user', pwd: 'nivaldo', roles:[{role:'readWrite', db:'projeto_t_db'}]});
        EOF
      "
